[pytest]
testpaths = tests

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: core business flows
    negative: negative / error / permission tests

addopts = -vs --disable-warnings --alluredir=allure-results --clean-alluredir